<form action="http://<?php echo $_SERVER['HTTP_HOST'];?>/application/Index/hostdoedit" method="post" 
enctype="multipart/form-data">
上传头像
<div>
<label for="file">Filename:</label>
<input type="file" name="file" id="file" /> 
<br />

用户id:<?php echo $h_id;?>
</br>
头像 <img src='<?php echo $imgsrc?>'>
</br>
用户名:<input type='text' value='<?php echo $username?>' name='username'>
</br>

电话:<input type='text' value='<?php echo $phone?>' name='phone'>
</br>
备注:<input type='textarea' value='<?php echo $extra?>' name='extra'>
</br>

<input type='submit'>

</form>

<a href="http://<?php echo $_SERVER['HTTP_HOST'];?>/application/Index/usermain">back_to_main</a>