<div class="sidebar">
<div class="photo">
<img src='<?php echo $imgsrc?>' width='152px' height='152px'>
</div>
<ul class="list">
<li>
<a href="http://<?php echo $_SERVER['HTTP_HOST'];?>/application/Index/usermain"><i class="icon-home scolor"></i>主页</a>
</li>
<li>
<a href="http://<?php echo $_SERVER['HTTP_HOST'];?>/application/Index/edituser"><i class="icon-user scolor"></i>编辑个人信息</a>
</li>
<li>
<a href="http://<?php echo $_SERVER['HTTP_HOST'];?>/application/Index/allactive"><i class="icon-list scolor"></i>所有活动列表</a>
</li>
<li>
<a href="http://<?php echo $_SERVER['HTTP_HOST'];?>/application/Index/searchactive"><i class="icon-heart scolor"></i>已经报名活动</a>
</li>
<li>
<a href="http://<?php echo $_SERVER['HTTP_HOST'];?>/application/Index/logout">logout</a>
</li>
</ul>
</div>

<div class="regist-container">
<h3 class="regist-title">修改信息</h3>
<form action="http://<?php echo $_SERVER['HTTP_HOST'];?>/application/Index/doedit" method="post" 
enctype="multipart/form-data">
<div class="upload-photo">
<img src='<?php echo $imgsrc?>' id="img0" width="148" height="148" >
<input type="button" class="upload-label" onclick="file.click()" value="上传图片"/>
<input class="upload-button" type="file" name="file" id="file" /> 
</div>

<div class="info">
<h4 class="info-title">基本信息</h4>
<div class="form-group">
用户id:<?php echo $u_id;?>
</div>
<div class="form-group">
用户名:<?php echo $username?>
</div>
<div class="form-group">
昵  称
<br/>
<input type='text' value='<?php echo $nickname?>' name='nickname'>
</div>
<div class="form-group">
性别
<br/>
<input type="radio" name='gender' value='1' <?php if($gender==1){echo 'checked';}?>>男</input>
<input class="ra2" type="radio" name='gender' value='2' <?php if($gender==2){echo 'checked';}?>>女</input>
</div>
<div class="form-group">
联系方式
<br/>
<input type='text' name='phone' value='<?php echo $phone?>'>
</div>
<div class="form-group">
备注
<br/>
<input type='textarea' name='extra' value='<?php echo $extra?>'>
</div>
</div>
<div class="regist-span">
<input class="upload-label" type='submit' value="保存">
</div>
</form>
</div>

 <script> 
    /**
18
     * 使用HTML5 File API, 來即時預覽image
19
     */
    $("#file").change(function(){
        var objUrl = getObjectURL(this.files[0]) ;
        if (objUrl) {
            $("#img0").attr("src", objUrl) ;
        }
    }) ;
    /**
     * 建立一個可存取到該file的url
     * PS: 瀏覽器必須支援HTML5 File API
     */
    function getObjectURL(file) {
        var url = null ;
        if (window.createObjectURL!=undefined) { // basic
            url = window.createObjectURL(file) ;
        } else if (window.URL!=undefined) { // mozilla(firefox)
            url = window.URL.createObjectURL(file) ;
        } else if (window.webkitURL!=undefined) { // webkit or chrome
            url = window.webkitURL.createObjectURL(file) ;
        }
        return url ;
    }
</script>
