<div class="sidebar">
<div class="photo">
<img src='<?php echo $imgsrc?>' width='152px' height='152px'>
</div>
<ul class="list">
<li>
<a href="http://<?php echo $_SERVER['HTTP_HOST'];?>/application/Index/hostmain"><i class="icon-home scolor"></i>主页</a>
</li>
<li>
<a href="http://<?php echo $_SERVER['HTTP_HOST'];?>/application/Index/edithost"><i class="icon-user scolor"></i>编辑主办方信息</a>
</li>
<li>
<a href="http://<?php echo $_SERVER['HTTP_HOST'];?>/application/Index/activelist"><i class="icon-list scolor"></i>所有活动列表</a>
</li>
<li>
<a href="http://<?php echo $_SERVER['HTTP_HOST'];?>/application/Index/signactive"><i class="icon-fire scolor"></i>创建活动</a>
</li>
<li>
<a href="http://<?php echo $_SERVER['HTTP_HOST'];?>/application/Index/logout">logout</a>
</li>
</ul>
</div>

用户id:<?php echo $_SESSION['h_id'];?>
</br>
</br>
用户名:<?php echo $username?>
</br>

电话:<?php echo $phone?>
</br>
备注:<?php echo $extra?>
</br>
<a href="http://<?php echo $_SERVER['HTTP_HOST'];?>/application/Index/edithost">edit_host</a>
</br>
<a href="http://<?php echo $_SERVER['HTTP_HOST'];?>/application/Index/signactive">signactive</a>
</br>
<a href="http://<?php echo $_SERVER['HTTP_HOST'];?>/application/Index/activelist">activelist</a>