
用户id:<?php echo $_SESSION['h_id'];?>
</br>
头像 <img src='<?php echo $imgsrc?>'>
</br>
用户名:<?php echo $username?>
</br>

电话:<?php echo $phone?>
</br>
备注:<?php echo $extra?>
</br>
<a href="http://<?php echo $_SERVER['HTTP_HOST'];?>/application/Index/edithost">edit_host</a>
</br>
<a href="http://<?php echo $_SERVER['HTTP_HOST'];?>/application/Index/signactive">signactive</a>
</br>
<a href="http://<?php echo $_SERVER['HTTP_HOST'];?>/application/Index/activelist">activelist</a>