<form class="welcome" action="http://<?php echo $_SERVER['HTTP_HOST'];?>/application/Index/login" method="post" >
<div class="login">
<input type="radio" name='type' value='1'>普通用户</input>
<input class ="ra2" type="radio" name='type' value='2'>举办方</input>
</div>
<div class="username-text">用户名:</div>
<div class="password-text">密码:</div>
<div class="username-field">
	<input class="input-username-field" type='text' name='username'/>
</div>
<div class="password-field">
	<input class="input-username-field" type='password' name='password'/>
</div>
<div class="regist">
<a href="http://<?php echo $_SERVER['HTTP_HOST'];?>/application/Index/regist">注册</a>
</div>
<div class="forgot-usr-pwd">忘记 <a href="#">用户名</a> 或 <a href="#">密码</a>?</div>
<input class="submit-login" type="submit" name="submit" value="GO" />
</form>