<form action="http://<?php echo $_SERVER['HTTP_HOST'];?>/application/Index/login" method="post" >
用户名：<input type='text' name='username'>
密  码：<input type='password' name='password'>
<br />
<input type="radio" name='type' value='1'>普通用户
<input type="radio" name='type' value='2'>举办方
<br />

<input type='submit'>
</form>

<a href="http://<?php echo $_SERVER['HTTP_HOST'];?>/application/Index/regist">注册</a>