<?php session_start(); 

if($result=='0'){?>
用户id:<?php echo $_SESSION['u_id'];?>
</br>
头像 <img src='<?php echo $imgsrc?>'>
</br>
用户名:<?php echo $username?>
</br>
昵称:<?php echo $nickname?>
</br>
性别:<?php 
if($gender==1)
{
echo '男';
}else
{
echo '女';
}?>
</br>
电话:<?php echo $phone?>
</br>
备注:<?php echo $extra?>
<?php }
else if($result=='1')
?>
不存在此用户
</br>
<a href="http://<?php echo $_SERVER['HTTP_HOST'];?>/application/Index/edituser">edit_info</a>