<div class="sidebar">
<div class="photo">
<img src='<?php echo $imgsrc?>' width='172px' height='172px'>
</div>
<ul class="list">
<li>
<a href="http://<?php echo $_SERVER['HTTP_HOST'];?>/application/Index/edituser"><i class="icon-glass scolor"></i>编辑个人信息</a>
</li>
<li>
<a href="http://<?php echo $_SERVER['HTTP_HOST'];?>/application/Index/allactive"><i class="icon-road scolor"></i>所有活动列表</a>
</li>
<li>
<a href="http://<?php echo $_SERVER['HTTP_HOST'];?>/application/Index/searchactive"><i class="icon-road scolor"></i>已经报名的活动</a>
</li>
</ul>
</div>
用户id:<?php echo $_SESSION['u_id'];?>
</br>
用户名:<?php echo $username?>
</br>
昵称:<?php echo $nickname?>
</br>
性别:<?php 
if($gender==1)
{
echo '男';
}else
{
echo '女';
}?>
</br>
电话:<?php echo $phone?>
</br>
备注:<?php echo $extra?>
</br>

</br>

</br>

